[package]
name = "electrico"
version = "0.5.0"
edition = "2021"
authors = ["Thomas Tschurtschenthaler"]
license = "MIT OR Apache-2.0"
description = "Lightweight Electron 'compatible' App Container."

[package.metadata.bundle.ttschurtschenthaler.downlet]
name = "Electrico"
identifier = "com.ttschurtschenthaler.electrico"
icon = ["icons/icon*.png"]
version = "1.0.0"
copyright = "Copyright (c) Thomas Tschurtschenthaler 2024. All rights reserved."
category = "App"
short_description = "Lightweight Electron 'compatible' App Container."
long_description = """
"""
[dependencies.uuid]
version = "1.3.0"
features = [
    "v4",
    "fast-rng",
    "macro-diagnostics"
]

[dependencies]
log = {version = "0.4.22"}
env_logger = {version = "0.11.5"}
include_dir = {version = "0.7.3"}
wry = { version = "0.43.1"}
tao = { version = "0.30.0"}
muda = {version = "0.14.1"}
serde_json = { version = "1.0.128"}
serde = {version = "1.0.210"}
rfd = {version="0.14.1"}
tokio = {version = "1.40.0", features = ["full"]}

reqwest = {version = "0.12.7"}
substring = {version = "1.4.5"}
open = {version = "5.3.0"}

mime_guess = {version = "2.0.5"}
lazy_static = {version = "1.5.0"}
base64 = {version = "0.22.1"}
directories = {version = "5.0.1"}

[target."cfg(target_os = \"windows\")".dependencies.windows-sys]
version = "0.59.0"
features = [
  "Win32_UI_WindowsAndMessaging",
  "Win32_Foundation",
  "Win32_Graphics_Gdi",
  "Win32_UI_Shell",
  "Win32_Globalization",
  "Win32_UI_Input_KeyboardAndMouse",
  "Win32_System_SystemServices",
  "Win32_UI_Accessibility",
  "Win32_UI_HiDpi",
  "Win32_System_LibraryLoader",
  "Win32_UI_Controls"
]

[target."cfg(target_os = \"linux\")".dependencies]
gtk = "0.18"
libxdo = { version = "0.6.0", optional = true }

[target."cfg(target_os = \"macos\")".dependencies]
cocoa = "0.26.0"
objc = "0.2"
png = "0.17"
